import type { Material, MaterialProfile } from './types';

/* ============================================================
   MATERIAL ARCHIVE — DEMONSTRATION RECORDS
   These are representative specimens, not a complete historical
   library. Every record carries a fidelity marking:

     documented      — behaviour derived from published data
     reconstructed   — assembled from partial references
     interpretation  — an artistic reading, not a reproduction

   Nothing here claims exact chemical reproduction.
   ============================================================ */

const base: MaterialProfile = {
  monochrome: false,
  monoMix: [0.299, 0.587, 0.114],
  toe: 0.3,
  shoulder: 0.4,
  gamma: 1,
  contrast: 0,
  latitude: 0.5,
  saturation: 1,
  channelGamma: [1, 1, 1],
  shadowTint: [0, 0, 0],
  highlightTint: [0, 0, 0],
  crossover: 0,
  grainSize: 0.4,
  grainDensity: 0.4,
  grainClump: 0.3,
  grainChroma: 0.2,
  halationTint: [1, 0.36, 0.16],
  halationBase: 0.3,
  bloom: 0.25,
};

const p = (over: Partial<MaterialProfile>): MaterialProfile => ({ ...base, ...over });

export const MATERIALS: Material[] = [
  /* ---------------- EARLY PROCESSES ---------------- */
  {
    id: 'daguerreotype',
    name: 'Daguerreotype',
    manufacturer: 'Daguerre / Giroux',
    archiveNo: 'PML-001',
    era: '1800s',
    yearFrom: 1839,
    yearTo: 1860,
    kind: 'early-process',
    formats: ['plate'],
    iso: null,
    isoLabel: '≈ ISO 0.5',
    fidelity: 'interpretation',
    traits: { grain: 0.05, contrast: 0.78, latitude: 0.12, sharpness: 0.95, saturation: 0.04 },
    profile: p({
      monochrome: true,
      monoMix: [0.12, 0.3, 0.58],
      toe: 0.62, shoulder: 0.2, gamma: 1.22, contrast: 0.34, latitude: 0.12,
      saturation: 0.05, shadowTint: [0.02, 0.03, 0.06], highlightTint: [0.06, 0.05, 0.02],
      grainSize: 0.08, grainDensity: 0.12, grainClump: 0.1, grainChroma: 0,
      halationTint: [0.85, 0.82, 0.72], halationBase: 0.5, bloom: 0.45,
    }),
    notes: {
      tonal: 'Extremely long scale in the highlights, abrupt in the shadows. The image is a mirror; tone depends on viewing angle.',
      grain: 'No grain structure in the film sense — a polished silver surface resolving detail down to the limit of the optics.',
      color: 'Monochrome, blue-sensitive only. Red and warm subjects render nearly black.',
      highlight: 'Specular, near-metallic. Highlights read as bare polished plate.',
      shadow: 'Dense and quick to close. Very little separation once the toe is reached.',
      history: 'The first commercially successful photographic process, announced in 1839. Direct positive on a silvered copper plate; each plate is unique and laterally reversed.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#191b20', '#7b7e80', '#d8d6cb'],
  },
  {
    id: 'wet-plate-collodion',
    name: 'Wet Plate Collodion',
    manufacturer: 'Archer process',
    archiveNo: 'PML-002',
    era: '1800s',
    yearFrom: 1851,
    yearTo: null,
    kind: 'early-process',
    formats: ['plate', 'large-format'],
    iso: null,
    isoLabel: '≈ ISO 1',
    fidelity: 'reconstructed',
    traits: { grain: 0.1, contrast: 0.7, latitude: 0.15, sharpness: 0.88, saturation: 0.05 },
    profile: p({
      monochrome: true,
      monoMix: [0.06, 0.26, 0.68],
      toe: 0.55, shoulder: 0.26, gamma: 1.15, contrast: 0.26, latitude: 0.16,
      saturation: 0.05, shadowTint: [0.03, 0.035, 0.05], highlightTint: [0.07, 0.06, 0.035],
      grainSize: 0.12, grainDensity: 0.18, grainClump: 0.5, grainChroma: 0,
      halationTint: [0.9, 0.8, 0.62], halationBase: 0.55, bloom: 0.5,
    }),
    notes: {
      tonal: 'Steep, luminous mid-scale with rapid shadow falloff. Skies render pale because of the blue sensitivity.',
      grain: 'No conventional grain. Texture comes from the pour: streaks, comets and edge irregularity from the collodion itself.',
      color: 'Blue and ultraviolet sensitive. Warm tones darken dramatically; freckles and lips go black.',
      highlight: 'Holds an enormous amount of highlight before blocking.',
      shadow: 'Empty. Shadows fall away quickly and stay empty.',
      history: 'Introduced by Frederick Scott Archer in 1851. The plate is coated, exposed and developed while still wet, which is why field photographers travelled with darkroom tents.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#1a1c1d', '#8d8b83', '#e6e2d6'],
  },
  {
    id: 'tintype',
    name: 'Tintype',
    manufacturer: 'Ferrotype plate',
    archiveNo: 'PML-003',
    era: '1800s',
    yearFrom: 1856,
    yearTo: null,
    kind: 'early-process',
    formats: ['plate'],
    iso: null,
    isoLabel: '≈ ISO 1',
    fidelity: 'reconstructed',
    traits: { grain: 0.12, contrast: 0.62, latitude: 0.2, sharpness: 0.72, saturation: 0.06 },
    profile: p({
      monochrome: true,
      monoMix: [0.08, 0.28, 0.64],
      toe: 0.5, shoulder: 0.34, gamma: 1.05, contrast: 0.14, latitude: 0.22,
      saturation: 0.06, shadowTint: [0.05, 0.045, 0.04], highlightTint: [0.08, 0.07, 0.05],
      grainSize: 0.16, grainDensity: 0.24, grainClump: 0.55, grainChroma: 0,
      halationTint: [0.86, 0.76, 0.6], halationBase: 0.45, bloom: 0.42,
    }),
    notes: {
      tonal: 'Softer and warmer than a glass plate. Shadows sit on the dark lacquered base rather than going fully black.',
      grain: 'Surface texture dominates: brush marks, dust in the varnish, small bare patches at the edges.',
      color: 'Monochrome with a warm, slightly brown cast from the japanned iron support.',
      highlight: 'Compressed. The plate rarely reaches a true paper white.',
      shadow: 'Deep but never neutral — always a little warm.',
      history: 'A direct positive on a thin sheet of lacquered iron. Cheap, durable and fast to deliver, which made it the portrait process of fairs, streets and battlefields.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#211d18', '#7e7466', '#ddd2bd'],
  },
  {
    id: 'cyanotype',
    name: 'Cyanotype',
    manufacturer: 'Herschel process',
    archiveNo: 'PML-004',
    era: '1800s',
    yearFrom: 1842,
    yearTo: null,
    kind: 'early-process',
    formats: ['plate', 'large-format'],
    iso: null,
    isoLabel: 'CONTACT',
    fidelity: 'interpretation',
    traits: { grain: 0.2, contrast: 0.5, latitude: 0.4, sharpness: 0.5, saturation: 0.3 },
    profile: p({
      monochrome: true,
      monoMix: [0.1, 0.32, 0.58],
      toe: 0.4, shoulder: 0.44, gamma: 0.94, contrast: 0.04, latitude: 0.42,
      saturation: 0.3,
      shadowTint: [-0.06, 0.0, 0.2], highlightTint: [0.05, 0.06, 0.04], crossover: 0.5,
      channelGamma: [1.18, 1.02, 0.82],
      grainSize: 0.3, grainDensity: 0.2, grainClump: 0.6, grainChroma: 0.05,
      halationTint: [0.5, 0.7, 1], halationBase: 0.3, bloom: 0.35,
    }),
    notes: {
      tonal: 'Long, gentle and low in contrast. The paper fibre is part of the image.',
      grain: 'Paper texture rather than grain. Coating brush marks read at the borders.',
      color: 'Prussian blue. Not a tint applied to a grey image — the image is the pigment.',
      highlight: 'Paper white, warm and slightly uneven where the coating thinned.',
      shadow: 'Saturated blue-black; can bronze in the deepest areas.',
      history: 'Described by John Herschel in 1842 and used by Anna Atkins for the first photographically illustrated book. Requires ultraviolet light and long contact exposures.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#0d2338', '#3f6d92', '#dcdcc9'],
  },

  /* ---------------- BLACK & WHITE ---------------- */
  {
    id: 'kodak-tri-x',
    name: 'Kodak Tri-X',
    manufacturer: 'Kodak',
    archiveNo: 'PML-011',
    era: '1950-1969',
    yearFrom: 1954,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 400,
    isoLabel: 'ISO 400',
    fidelity: 'documented',
    traits: { grain: 0.72, contrast: 0.6, latitude: 0.7, sharpness: 0.62, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.28, 0.6, 0.12],
      toe: 0.3, shoulder: 0.52, gamma: 1.04, contrast: 0.16, latitude: 0.7,
      saturation: 0,
      shadowTint: [0.012, 0.008, 0.0], highlightTint: [0.02, 0.018, 0.012],
      grainSize: 0.56, grainDensity: 0.66, grainClump: 0.44, grainChroma: 0,
      halationTint: [0.9, 0.85, 0.78], halationBase: 0.22, bloom: 0.2,
    }),
    notes: {
      tonal: 'Robust mid-scale with a long, forgiving shoulder. Pushes well because the curve keeps climbing.',
      grain: 'Distinct, sharp-edged and structural. The grain is part of the picture, not a defect to be hidden.',
      color: 'Panchromatic. Reds render slightly darker than the eye expects, which is why it flatters skin under hard light.',
      highlight: 'Very hard to blow out. Highlights compress rather than clip.',
      shadow: 'Holds detail well below the metered shadow, especially in a compensating developer.',
      history: 'Introduced in 1954 and reformulated several times since. The reportage and street standard for half a century.',
    },
    development: ['normal', 'push', 'pull', 'stand', 'bleach-bypass'],
    developers: ['d76', 'rodinal', 'hc110', 'xtol'],
    swatch: ['#171614', '#7d7a74', '#e8e5dd'],
  },
  {
    id: 'kodak-plus-x',
    name: 'Kodak Plus-X',
    manufacturer: 'Kodak',
    archiveNo: 'PML-012',
    era: '1950-1969',
    yearFrom: 1954,
    yearTo: 2011,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format'],
    iso: 125,
    isoLabel: 'ISO 125',
    fidelity: 'documented',
    traits: { grain: 0.34, contrast: 0.5, latitude: 0.62, sharpness: 0.75, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.3, 0.59, 0.11],
      toe: 0.26, shoulder: 0.46, gamma: 1, contrast: 0.06, latitude: 0.62,
      saturation: 0, shadowTint: [0.008, 0.008, 0.004], highlightTint: [0.015, 0.015, 0.012],
      grainSize: 0.3, grainDensity: 0.34, grainClump: 0.3, grainChroma: 0,
      halationTint: [0.88, 0.85, 0.8], halationBase: 0.18, bloom: 0.16,
    }),
    notes: {
      tonal: 'Even and slightly cooler than Tri-X. A calm, descriptive negative.',
      grain: 'Fine and unobtrusive at normal enlargement.',
      color: 'Panchromatic, neutral rendering.',
      highlight: 'Clean separation up to a gentle shoulder.',
      shadow: 'Requires accurate exposure — less generous than the 400 speed stock.',
      history: 'Kodak\'s medium-speed panchromatic companion to Tri-X, discontinued in 2011.',
    },
    development: ['normal', 'push', 'pull', 'stand'],
    developers: ['d76', 'rodinal', 'hc110', 'xtol'],
    swatch: ['#141413', '#7f7d79', '#eae8e2'],
  },
  {
    id: 'ilford-hp5',
    name: 'Ilford HP5 Plus',
    manufacturer: 'Ilford',
    archiveNo: 'PML-013',
    era: '1970-1989',
    yearFrom: 1989,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 400,
    isoLabel: 'ISO 400',
    fidelity: 'documented',
    traits: { grain: 0.66, contrast: 0.44, latitude: 0.82, sharpness: 0.56, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.26, 0.6, 0.14],
      toe: 0.36, shoulder: 0.56, gamma: 0.96, contrast: 0.02, latitude: 0.82,
      saturation: 0, shadowTint: [0.006, 0.008, 0.01], highlightTint: [0.014, 0.014, 0.015],
      grainSize: 0.52, grainDensity: 0.6, grainClump: 0.5, grainChroma: 0,
      halationTint: [0.85, 0.84, 0.82], halationBase: 0.2, bloom: 0.2,
    }),
    notes: {
      tonal: 'Softer and flatter than Tri-X out of the tank, which makes it very controllable in the print.',
      grain: 'Slightly softer edged, a touch more clumped. Handsome when pushed hard.',
      color: 'Panchromatic and comparatively neutral across the spectrum.',
      highlight: 'Long shoulder; very difficult to lose highlight information.',
      shadow: 'Exceptional latitude. Tolerates several stops of underexposure with development compensation.',
      history: 'The current member of Ilford\'s HP line, whose ancestry runs back to Hypersensitive Panchromatic in the 1930s.',
    },
    development: ['normal', 'push', 'pull', 'stand', 'bleach-bypass'],
    developers: ['d76', 'rodinal', 'hc110', 'xtol'],
    swatch: ['#181817', '#7b7a77', '#e6e5e0'],
  },
  {
    id: 'ilford-fp4',
    name: 'Ilford FP4 Plus',
    manufacturer: 'Ilford',
    archiveNo: 'PML-014',
    era: '1990-2009',
    yearFrom: 1990,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 125,
    isoLabel: 'ISO 125',
    fidelity: 'documented',
    traits: { grain: 0.28, contrast: 0.52, latitude: 0.7, sharpness: 0.8, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.28, 0.6, 0.12],
      toe: 0.24, shoulder: 0.48, gamma: 1.02, contrast: 0.1, latitude: 0.7,
      saturation: 0, shadowTint: [0.006, 0.008, 0.009], highlightTint: [0.014, 0.014, 0.014],
      grainSize: 0.26, grainDensity: 0.3, grainClump: 0.26, grainChroma: 0,
      halationTint: [0.86, 0.85, 0.83], halationBase: 0.16, bloom: 0.14,
    }),
    notes: {
      tonal: 'Crisp and orderly. A studio and landscape negative rather than a reportage one.',
      grain: 'Very fine, tight and even.',
      color: 'Panchromatic, neutral.',
      highlight: 'Clean, well-separated highlights that hold texture.',
      shadow: 'Good but not limitless; rewards a metered shadow reading.',
      history: 'Ilford\'s fine-grain medium-speed emulsion, in production in its current form since 1990.',
    },
    development: ['normal', 'push', 'pull', 'stand'],
    developers: ['d76', 'rodinal', 'hc110', 'xtol'],
    swatch: ['#131313', '#7e7e7b', '#eceae5'],
  },
  {
    id: 'fuji-neopan',
    name: 'Fuji Neopan Acros',
    manufacturer: 'Fuji',
    archiveNo: 'PML-015',
    era: '1990-2009',
    yearFrom: 2001,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'documented',
    traits: { grain: 0.16, contrast: 0.58, latitude: 0.55, sharpness: 0.9, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.3, 0.62, 0.08],
      toe: 0.2, shoulder: 0.42, gamma: 1.06, contrast: 0.16, latitude: 0.55,
      saturation: 0, shadowTint: [0.004, 0.007, 0.012], highlightTint: [0.012, 0.013, 0.015],
      grainSize: 0.16, grainDensity: 0.2, grainClump: 0.18, grainChroma: 0,
      halationTint: [0.82, 0.83, 0.85], halationBase: 0.12, bloom: 0.12,
    }),
    notes: {
      tonal: 'Cool, smooth and modern. Very clean separation in the upper mid-tones.',
      grain: 'Almost absent at normal enlargement — the finest grain of the demonstration set.',
      color: 'Panchromatic with an unusually even spectral response.',
      highlight: 'Bright and clinical; will clip if overexposed.',
      shadow: 'Notably free of reciprocity failure on long exposures.',
      history: 'A late-generation fine-grain emulsion, known for night and long-exposure work.',
    },
    development: ['normal', 'push', 'pull', 'stand'],
    developers: ['d76', 'rodinal', 'xtol'],
    swatch: ['#111214', '#7c7e80', '#eeeeec'],
  },

  /* ---------------- COLOR ---------------- */
  {
    id: 'kodachrome',
    name: 'Kodachrome 64',
    manufacturer: 'Kodak',
    archiveNo: 'PML-021',
    era: '1930-1949',
    yearFrom: 1935,
    yearTo: 2009,
    kind: 'color-reversal',
    formats: ['35mm', 'super-8', '16mm'],
    iso: 64,
    isoLabel: 'ISO 64',
    fidelity: 'reconstructed',
    traits: { grain: 0.3, contrast: 0.74, latitude: 0.2, sharpness: 0.86, saturation: 0.68 },
    profile: p({
      toe: 0.42, shoulder: 0.22, gamma: 1.14, contrast: 0.3, latitude: 0.2,
      saturation: 1.12,
      channelGamma: [0.94, 1.0, 1.08],
      shadowTint: [0.02, 0.0, -0.02], highlightTint: [0.03, 0.015, -0.01], crossover: 0.22,
      grainSize: 0.24, grainDensity: 0.3, grainClump: 0.3, grainChroma: 0.14,
      halationTint: [1, 0.42, 0.2], halationBase: 0.24, bloom: 0.2,
    }),
    notes: {
      tonal: 'Reversal contrast: no room for error. Dense blacks, brilliant mid-tones, a very short shoulder.',
      grain: 'Fine and tight, with a characteristic crispness from the dye-coupler process.',
      color: 'Warm reds and ochres, restrained cyans, and a red that no other stock quite matched.',
      highlight: 'Unforgiving. A third of a stop over and the highlight is gone.',
      shadow: 'Deep, saturated and slightly warm rather than neutral.',
      history: 'Introduced in 1935. The dyes were added during processing rather than being present in the film, which is why it could only be developed in a handful of laboratories worldwide. Discontinued in 2009.',
    },
    development: ['normal', 'cross-process'],
    developers: ['stock'],
    swatch: ['#14100e', '#9a6a4a', '#f2e4cf'],
  },
  {
    id: 'kodak-ektachrome',
    name: 'Kodak Ektachrome E100',
    manufacturer: 'Kodak',
    archiveNo: 'PML-022',
    era: '1950-1969',
    yearFrom: 1946,
    yearTo: null,
    kind: 'color-reversal',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'documented',
    traits: { grain: 0.26, contrast: 0.7, latitude: 0.24, sharpness: 0.88, saturation: 0.62 },
    profile: p({
      toe: 0.4, shoulder: 0.24, gamma: 1.1, contrast: 0.26, latitude: 0.24,
      saturation: 1.08,
      channelGamma: [1.0, 1.0, 0.96],
      shadowTint: [-0.01, 0.0, 0.03], highlightTint: [0.0, 0.01, 0.02], crossover: 0.16,
      grainSize: 0.22, grainDensity: 0.26, grainClump: 0.26, grainChroma: 0.16,
      halationTint: [1, 0.45, 0.24], halationBase: 0.22, bloom: 0.2,
    }),
    notes: {
      tonal: 'Clean reversal scale, slightly cooler and more neutral than Kodachrome.',
      grain: 'Fine, even, and well behaved in scanning.',
      color: 'Accurate and cool-leaning, with clean blues and controlled greens.',
      highlight: 'Short shoulder — expose for the highlight, always.',
      shadow: 'Dense, cool, and quick to close.',
      history: 'Kodak\'s E-6 compatible transparency line, reintroduced in 2018 after being discontinued.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['e6', 'c41'],
    swatch: ['#0f1114', '#5f7b86', '#eef0ee'],
  },
  {
    id: 'kodak-portra',
    name: 'Kodak Portra 400',
    manufacturer: 'Kodak',
    archiveNo: 'PML-023',
    era: '1990-2009',
    yearFrom: 1998,
    yearTo: null,
    kind: 'color-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 400,
    isoLabel: 'ISO 400',
    fidelity: 'documented',
    traits: { grain: 0.42, contrast: 0.32, latitude: 0.9, sharpness: 0.7, saturation: 0.42 },
    profile: p({
      toe: 0.3, shoulder: 0.6, gamma: 0.94, contrast: -0.1, latitude: 0.9,
      saturation: 0.9,
      channelGamma: [0.97, 1.0, 1.04],
      shadowTint: [0.012, 0.008, 0.02], highlightTint: [0.035, 0.022, 0.006], crossover: 0.3,
      grainSize: 0.36, grainDensity: 0.4, grainClump: 0.3, grainChroma: 0.34,
      halationTint: [1, 0.4, 0.2], halationBase: 0.32, bloom: 0.3,
    }),
    notes: {
      tonal: 'Low contrast with an extremely long shoulder. Built to protect skin and highlight.',
      grain: 'Moderate, soft-edged, and colour-bearing rather than purely luminance.',
      color: 'Restrained saturation, warm highlights, and a slight cool drift in the shadows.',
      highlight: 'Practically impossible to clip. Overexposure raises density and softens colour rather than destroying it.',
      shadow: 'Open and slightly cool. Underexposure shows as chroma noise before it shows as blocking.',
      history: 'The portrait line introduced in 1998 and reformulated in 2010 with finer grain and a wider scanning latitude.',
    },
    development: ['normal', 'push', 'pull', 'cross-process', 'bleach-bypass'],
    developers: ['c41', 'e6'],
    swatch: ['#1a1613', '#a4816c', '#f6ece0'],
  },
  {
    id: 'kodak-gold',
    name: 'Kodak Gold 200',
    manufacturer: 'Kodak',
    archiveNo: 'PML-024',
    era: '1970-1989',
    yearFrom: 1986,
    yearTo: null,
    kind: 'color-negative',
    formats: ['35mm', 'medium-format'],
    iso: 200,
    isoLabel: 'ISO 200',
    fidelity: 'documented',
    traits: { grain: 0.5, contrast: 0.46, latitude: 0.72, sharpness: 0.56, saturation: 0.6 },
    profile: p({
      toe: 0.28, shoulder: 0.5, gamma: 0.98, contrast: 0.06, latitude: 0.72,
      saturation: 1.06,
      channelGamma: [0.9, 0.99, 1.1],
      shadowTint: [0.03, 0.012, 0.0], highlightTint: [0.06, 0.035, -0.01], crossover: 0.44,
      grainSize: 0.42, grainDensity: 0.5, grainClump: 0.36, grainChroma: 0.44,
      halationTint: [1, 0.42, 0.18], halationBase: 0.38, bloom: 0.32,
    }),
    notes: {
      tonal: 'Cheerful and slightly punchy. Mid-tones sit warm.',
      grain: 'Visible at 35mm, loose and colourful. Part of the look rather than a fault.',
      color: 'Golden highlights, strong yellows, and reds that lean orange.',
      highlight: 'Warm and generous; blows to cream rather than white.',
      shadow: 'Muddy-warm when underexposed, which is exactly what most people remember it as.',
      history: 'The consumer colour negative that photographed most of the late twentieth century.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['c41'],
    swatch: ['#1c1610', '#ab8452', '#faeed0'],
  },
  {
    id: 'kodak-ektar',
    name: 'Kodak Ektar 100',
    manufacturer: 'Kodak',
    archiveNo: 'PML-025',
    era: '2010-present',
    yearFrom: 2008,
    yearTo: null,
    kind: 'color-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'documented',
    traits: { grain: 0.14, contrast: 0.6, latitude: 0.6, sharpness: 0.92, saturation: 0.8 },
    profile: p({
      toe: 0.26, shoulder: 0.44, gamma: 1.04, contrast: 0.18, latitude: 0.6,
      saturation: 1.24,
      channelGamma: [0.96, 1.0, 1.02],
      shadowTint: [0.0, 0.004, 0.018], highlightTint: [0.018, 0.012, 0.0], crossover: 0.18,
      grainSize: 0.16, grainDensity: 0.18, grainClump: 0.2, grainChroma: 0.24,
      halationTint: [1, 0.38, 0.16], halationBase: 0.26, bloom: 0.22,
    }),
    notes: {
      tonal: 'The most contrast of the colour negatives here, closer to a transparency in feel.',
      grain: 'Extremely fine — the finest-grained colour negative in the demonstration set.',
      color: 'High saturation with strong reds and deep blues. Skin can go ruddy under warm light.',
      highlight: 'Cleaner and shorter than Portra; will actually clip.',
      shadow: 'Deep and saturated with good neutrality.',
      history: 'Introduced in 2008 as a landscape and product negative aimed at scanning workflows.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['c41'],
    swatch: ['#131311', '#8a6f56', '#f6f1e4'],
  },
  {
    id: 'fuji-velvia',
    name: 'Fuji Velvia 50',
    manufacturer: 'Fuji',
    archiveNo: 'PML-026',
    era: '1990-2009',
    yearFrom: 1990,
    yearTo: null,
    kind: 'color-reversal',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 50,
    isoLabel: 'ISO 50',
    fidelity: 'documented',
    traits: { grain: 0.16, contrast: 0.86, latitude: 0.14, sharpness: 0.94, saturation: 0.98 },
    profile: p({
      toe: 0.46, shoulder: 0.18, gamma: 1.2, contrast: 0.4, latitude: 0.14,
      saturation: 1.42,
      channelGamma: [0.92, 1.02, 1.0],
      shadowTint: [-0.02, 0.0, 0.04], highlightTint: [0.02, 0.02, -0.01], crossover: 0.24,
      grainSize: 0.14, grainDensity: 0.18, grainClump: 0.2, grainChroma: 0.14,
      halationTint: [1, 0.4, 0.22], halationBase: 0.2, bloom: 0.18,
    }),
    notes: {
      tonal: 'Very steep. Roughly five usable stops and no argument about it.',
      grain: 'Almost invisible. Detail is limited by the lens, not the emulsion.',
      color: 'Famously intense greens and reds. Not a neutral film and never pretended to be.',
      highlight: 'Clips hard and early.',
      shadow: 'Blocks to a saturated near-black, often with a blue cast.',
      history: 'Released in 1990 and immediately adopted by landscape photographers for its saturation.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['e6', 'c41'],
    swatch: ['#0a1110', '#3f6f4c', '#f0f2e4'],
  },
  {
    id: 'fuji-provia',
    name: 'Fuji Provia 100F',
    manufacturer: 'Fuji',
    archiveNo: 'PML-027',
    era: '1990-2009',
    yearFrom: 1994,
    yearTo: null,
    kind: 'color-reversal',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'documented',
    traits: { grain: 0.18, contrast: 0.64, latitude: 0.3, sharpness: 0.9, saturation: 0.56 },
    profile: p({
      toe: 0.36, shoulder: 0.3, gamma: 1.06, contrast: 0.2, latitude: 0.3,
      saturation: 1.02,
      channelGamma: [1.0, 1.0, 0.98],
      shadowTint: [-0.008, 0.0, 0.024], highlightTint: [0.0, 0.008, 0.014], crossover: 0.12,
      grainSize: 0.16, grainDensity: 0.2, grainClump: 0.22, grainChroma: 0.14,
      halationTint: [1, 0.44, 0.26], halationBase: 0.2, bloom: 0.18,
    }),
    notes: {
      tonal: 'The even-tempered transparency. Enough contrast to sparkle, enough scale to survive a bright day.',
      grain: 'Very fine and neutral.',
      color: 'Balanced, slightly cool, and reliable under mixed light.',
      highlight: 'More shoulder than Velvia; usable specular detail.',
      shadow: 'Clean and cool with reasonable separation.',
      history: 'Fuji\'s general-purpose E-6 transparency film, in production since the mid-1990s.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['e6', 'c41'],
    swatch: ['#0e1013', '#5c7382', '#eff1f1'],
  },

  /* ---------------- INSTANT ---------------- */
  {
    id: 'polaroid-sx70',
    name: 'Polaroid SX-70',
    manufacturer: 'Polaroid',
    archiveNo: 'PML-031',
    era: '1970-1989',
    yearFrom: 1972,
    yearTo: null,
    kind: 'instant',
    formats: ['instant'],
    iso: 160,
    isoLabel: 'ISO 160',
    fidelity: 'reconstructed',
    traits: { grain: 0.3, contrast: 0.4, latitude: 0.3, sharpness: 0.42, saturation: 0.44 },
    profile: p({
      toe: 0.44, shoulder: 0.56, gamma: 0.9, contrast: -0.06, latitude: 0.3,
      saturation: 0.86,
      channelGamma: [0.94, 1.0, 1.1],
      shadowTint: [0.05, 0.035, 0.02], highlightTint: [0.06, 0.045, 0.02], crossover: 0.5,
      grainSize: 0.34, grainDensity: 0.26, grainClump: 0.62, grainChroma: 0.4,
      halationTint: [1, 0.55, 0.3], halationBase: 0.42, bloom: 0.55,
    }),
    notes: {
      tonal: 'Low contrast, lifted blacks, and a soft creamy highlight. The image sits on the surface.',
      grain: 'Not grain in the silver sense — dye-cloud mottling and uneven development across the frame.',
      color: 'Warm, pastel, and slightly faded from the moment it developed.',
      highlight: 'Soft and diffuse, with heavy bloom around light sources.',
      shadow: 'Never black. There is always a milky floor.',
      history: 'The integral film introduced with the folding SX-70 camera in 1972 — developed in daylight, in the hand, with no peel-apart step.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#2b2622', '#a08670', '#f4e6d2'],
  },
  {
    id: 'polaroid-600',
    name: 'Polaroid 600',
    manufacturer: 'Polaroid',
    archiveNo: 'PML-032',
    era: '1970-1989',
    yearFrom: 1981,
    yearTo: null,
    kind: 'instant',
    formats: ['instant'],
    iso: 640,
    isoLabel: 'ISO 640',
    fidelity: 'reconstructed',
    traits: { grain: 0.44, contrast: 0.52, latitude: 0.26, sharpness: 0.36, saturation: 0.56 },
    profile: p({
      toe: 0.4, shoulder: 0.5, gamma: 0.94, contrast: 0.08, latitude: 0.26,
      saturation: 0.94,
      channelGamma: [0.92, 1.0, 1.08],
      shadowTint: [0.05, 0.04, 0.035], highlightTint: [0.07, 0.05, 0.02], crossover: 0.56,
      grainSize: 0.42, grainDensity: 0.36, grainClump: 0.68, grainChroma: 0.5,
      halationTint: [1, 0.5, 0.28], halationBase: 0.5, bloom: 0.66,
    }),
    notes: {
      tonal: 'Punchier than SX-70 and usually flash-lit, which shortens the scale further.',
      grain: 'Coarser mottling, with visible chemistry streaks near the edges.',
      color: 'Cooler in the shadows, warm in the highlight, with strong crossover.',
      highlight: 'Blooms aggressively around any direct light source.',
      shadow: 'Lifted, slightly green, and noisy.',
      history: 'The faster integral film introduced in 1981 for built-in-flash cameras.',
    },
    development: ['normal'],
    developers: ['stock'],
    swatch: ['#2e2b28', '#9d8874', '#f6ebd8'],
  },

  /* ---------------- MOTION PICTURE ---------------- */
  {
    id: 'kodak-vision3-500t',
    name: 'Kodak Vision3 500T',
    manufacturer: 'Kodak',
    archiveNo: 'PML-041',
    era: '2010-present',
    yearFrom: 2007,
    yearTo: null,
    kind: 'motion-picture',
    formats: ['35mm', '16mm', 'super-8'],
    iso: 500,
    isoLabel: 'ISO 500T',
    fidelity: 'documented',
    traits: { grain: 0.5, contrast: 0.3, latitude: 0.94, sharpness: 0.72, saturation: 0.44 },
    profile: p({
      toe: 0.3, shoulder: 0.66, gamma: 0.9, contrast: -0.14, latitude: 0.94,
      saturation: 0.9,
      channelGamma: [0.98, 1.0, 1.06],
      shadowTint: [0.0, 0.006, 0.03], highlightTint: [0.03, 0.02, 0.0], crossover: 0.26,
      grainSize: 0.4, grainDensity: 0.46, grainClump: 0.3, grainChroma: 0.36,
      halationTint: [1, 0.3, 0.12], halationBase: 0.62, bloom: 0.34,
    }),
    notes: {
      tonal: 'Enormous latitude and a very long shoulder — designed to be graded, not printed straight.',
      grain: 'Fine for the speed, with a smooth, almost fluid structure in motion.',
      color: 'Tungsten balanced. Under daylight it goes decisively blue without correction.',
      highlight: 'Extremely protective. Practical lights hold colour far past where a still negative would clip.',
      shadow: 'Deep with usable detail several stops down.',
      history: 'Part of the Vision3 family introduced from 2007. The removal of the remjet backing during processing is why scanned Vision stock shows such pronounced halation around practical lights.',
    },
    development: ['normal', 'push', 'pull', 'bleach-bypass', 'cross-process'],
    developers: ['c41', 'stock'],
    swatch: ['#101418', '#6d7a80', '#f0eee8'],
  },
  {
    id: 'super-8-color',
    name: 'Super 8 Colour Reversal',
    manufacturer: 'Kodak',
    archiveNo: 'PML-042',
    era: '1970-1989',
    yearFrom: 1965,
    yearTo: null,
    kind: 'motion-picture',
    formats: ['super-8'],
    iso: 160,
    isoLabel: 'ISO 160',
    fidelity: 'reconstructed',
    traits: { grain: 0.86, contrast: 0.66, latitude: 0.24, sharpness: 0.3, saturation: 0.6 },
    profile: p({
      toe: 0.42, shoulder: 0.3, gamma: 1.08, contrast: 0.24, latitude: 0.24,
      saturation: 1.06,
      channelGamma: [0.94, 1.0, 1.06],
      shadowTint: [0.03, 0.02, 0.01], highlightTint: [0.05, 0.03, 0.0], crossover: 0.42,
      grainSize: 0.78, grainDensity: 0.76, grainClump: 0.52, grainChroma: 0.5,
      halationTint: [1, 0.42, 0.2], halationBase: 0.4, bloom: 0.4,
    }),
    notes: {
      tonal: 'Short scale with a bright, contrasty projection look.',
      grain: 'Very large relative to the frame — the whole point of the format.',
      color: 'Warm and nostalgic, with heavy crossover after decades of storage.',
      highlight: 'Clips readily and blooms.',
      shadow: 'Dense and noisy.',
      history: 'The cartridge format introduced in 1965 that made home movie-making genuinely domestic.',
    },
    development: ['normal', 'push', 'cross-process'],
    developers: ['stock', 'e6'],
    swatch: ['#1c1712', '#a07a4e', '#f7ecd6'],
  },
  {
    id: 'bw-16mm',
    name: '16mm B&W Reversal',
    manufacturer: 'Kodak',
    archiveNo: 'PML-043',
    era: '1930-1949',
    yearFrom: 1923,
    yearTo: null,
    kind: 'motion-picture',
    formats: ['16mm'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'reconstructed',
    traits: { grain: 0.66, contrast: 0.72, latitude: 0.28, sharpness: 0.44, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.26, 0.6, 0.14],
      toe: 0.44, shoulder: 0.28, gamma: 1.14, contrast: 0.3, latitude: 0.28,
      saturation: 0, shadowTint: [0.02, 0.018, 0.012], highlightTint: [0.03, 0.026, 0.016],
      grainSize: 0.6, grainDensity: 0.62, grainClump: 0.48, grainChroma: 0,
      halationTint: [0.9, 0.78, 0.62], halationBase: 0.3, bloom: 0.3,
    }),
    notes: {
      tonal: 'Reversal contrast in monochrome: bright, graphic and quick to close.',
      grain: 'Coarse and active, moving frame to frame.',
      color: 'Monochrome with a warm archival cast.',
      highlight: 'Burns out with a soft flare.',
      shadow: 'Blocks early and stays there.',
      history: '16mm was introduced in 1923 as a non-theatrical amateur and documentary gauge, and became the standard for news and television field work.',
    },
    development: ['normal', 'push', 'pull'],
    developers: ['stock', 'd76'],
    swatch: ['#151311', '#7e786d', '#ece5d6'],
  },

  /* ---------------- OTHER MANUFACTURERS ---------------- */
  {
    id: 'agfa-apx',
    name: 'Agfa APX 100',
    manufacturer: 'Agfa',
    archiveNo: 'PML-051',
    era: '1990-2009',
    yearFrom: 1995,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format'],
    iso: 100,
    isoLabel: 'ISO 100',
    fidelity: 'reconstructed',
    traits: { grain: 0.26, contrast: 0.56, latitude: 0.58, sharpness: 0.84, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.3, 0.58, 0.12],
      toe: 0.24, shoulder: 0.44, gamma: 1.04, contrast: 0.14, latitude: 0.58,
      saturation: 0, shadowTint: [0.008, 0.008, 0.006], highlightTint: [0.016, 0.015, 0.012],
      grainSize: 0.24, grainDensity: 0.28, grainClump: 0.28, grainChroma: 0,
      halationTint: [0.88, 0.84, 0.78], halationBase: 0.16, bloom: 0.14,
    }),
    notes: {
      tonal: 'Bright and slightly brittle, with a distinctive snap in the upper mid-tones.',
      grain: 'Fine and sharp-edged.',
      color: 'Panchromatic, neutral to slightly warm.',
      highlight: 'Crisp with a short shoulder.',
      shadow: 'Clean but shallow.',
      history: 'A German fine-grain emulsion whose formulation and manufacture changed hands several times after 2005.',
    },
    development: ['normal', 'push', 'pull', 'stand'],
    developers: ['rodinal', 'd76', 'hc110'],
    swatch: ['#141312', '#807c74', '#eae7de'],
  },
  {
    id: 'foma-fomapan',
    name: 'Foma Fomapan 400',
    manufacturer: 'Foma',
    archiveNo: 'PML-052',
    era: '1990-2009',
    yearFrom: 1992,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format', 'large-format'],
    iso: 400,
    isoLabel: 'ISO 400',
    fidelity: 'reconstructed',
    traits: { grain: 0.82, contrast: 0.48, latitude: 0.5, sharpness: 0.5, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.28, 0.58, 0.14],
      toe: 0.34, shoulder: 0.46, gamma: 0.98, contrast: 0.04, latitude: 0.5,
      saturation: 0, shadowTint: [0.014, 0.012, 0.008], highlightTint: [0.024, 0.022, 0.016],
      grainSize: 0.72, grainDensity: 0.76, grainClump: 0.6, grainChroma: 0,
      halationTint: [0.9, 0.82, 0.72], halationBase: 0.26, bloom: 0.24,
    }),
    notes: {
      tonal: 'Older-generation curve: soft shoulder, warm mid-tones, a slightly antique feel straight out of the tank.',
      grain: 'Large, irregular and clumped. The most textural black and white in the set.',
      color: 'Panchromatic with a slight warmth.',
      highlight: 'Rolls off gently.',
      shadow: 'True speed sits below the box rating; shadows need help.',
      history: 'Manufactured in Hradec Králové. Traditional cubic-grain emulsion technology maintained largely unchanged.',
    },
    development: ['normal', 'push', 'pull', 'stand'],
    developers: ['rodinal', 'd76', 'hc110'],
    swatch: ['#181614', '#7d7669', '#e9e3d6'],
  },
  {
    id: 'orwo-np20',
    name: 'ORWO NP20',
    manufacturer: 'ORWO',
    archiveNo: 'PML-053',
    era: '1950-1969',
    yearFrom: 1964,
    yearTo: null,
    kind: 'bw-negative',
    formats: ['35mm', 'medium-format'],
    iso: 80,
    isoLabel: 'ISO 80',
    fidelity: 'reconstructed',
    traits: { grain: 0.44, contrast: 0.64, latitude: 0.4, sharpness: 0.7, saturation: 0 },
    profile: p({
      monochrome: true,
      monoMix: [0.24, 0.58, 0.18],
      toe: 0.38, shoulder: 0.36, gamma: 1.08, contrast: 0.2, latitude: 0.4,
      saturation: 0, shadowTint: [0.012, 0.012, 0.014], highlightTint: [0.02, 0.02, 0.02],
      grainSize: 0.4, grainDensity: 0.44, grainClump: 0.42, grainChroma: 0,
      halationTint: [0.86, 0.82, 0.76], halationBase: 0.22, bloom: 0.2,
    }),
    notes: {
      tonal: 'Contrasty and graphic, with an austere grey scale.',
      grain: 'Medium, defined, and slightly clustered.',
      color: 'Panchromatic, cool neutral.',
      highlight: 'Short shoulder; blocks cleanly.',
      shadow: 'Firm and quick.',
      history: 'Produced at Wolfen in the German Democratic Republic. Widely used across Eastern Europe until the 1990s.',
    },
    development: ['normal', 'push', 'pull'],
    developers: ['d76', 'rodinal'],
    swatch: ['#131415', '#7a7a78', '#e6e6e2'],
  },
  {
    id: 'lomography-redscale',
    name: 'Lomography Redscale',
    manufacturer: 'Lomography',
    archiveNo: 'PML-054',
    era: '2010-present',
    yearFrom: 2010,
    yearTo: null,
    kind: 'experimental',
    formats: ['35mm', 'medium-format'],
    iso: 100,
    isoLabel: 'ISO 100 / 50',
    fidelity: 'interpretation',
    traits: { grain: 0.6, contrast: 0.6, latitude: 0.3, sharpness: 0.5, saturation: 0.7 },
    profile: p({
      toe: 0.36, shoulder: 0.42, gamma: 1.02, contrast: 0.12, latitude: 0.3,
      saturation: 0.9,
      channelGamma: [0.72, 1.06, 1.5],
      shadowTint: [0.1, 0.02, -0.03], highlightTint: [0.14, 0.05, -0.05], crossover: 0.8,
      grainSize: 0.52, grainDensity: 0.56, grainClump: 0.44, grainChroma: 0.4,
      halationTint: [1, 0.3, 0.1], halationBase: 0.44, bloom: 0.34,
    }),
    notes: {
      tonal: 'Compressed and heavy. The blue record does almost no work.',
      grain: 'Coarse and warm, concentrated in the red layer.',
      color: 'Everything from amber to deep red, depending on exposure. More light means more yellow.',
      highlight: 'Golden, then orange, then gone.',
      shadow: 'Dense red-black.',
      history: 'Colour negative film loaded backwards so that light strikes the base before the emulsion. A deliberate misuse turned into a product.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['c41'],
    swatch: ['#2a0f06', '#a4441a', '#f6c268'],
  },
  {
    id: 'expired-stock',
    name: 'Expired Colour Stock',
    manufacturer: 'Unmarked',
    archiveNo: 'PML-061',
    era: '1990-2009',
    yearFrom: 1998,
    yearTo: 2004,
    kind: 'experimental',
    formats: ['35mm', 'medium-format'],
    iso: 200,
    isoLabel: 'ISO 200 (rated 100)',
    fidelity: 'interpretation',
    traits: { grain: 0.74, contrast: 0.3, latitude: 0.44, sharpness: 0.44, saturation: 0.34 },
    profile: p({
      toe: 0.5, shoulder: 0.56, gamma: 0.88, contrast: -0.2, latitude: 0.44,
      saturation: 0.7,
      channelGamma: [0.88, 1.02, 1.16],
      shadowTint: [0.07, 0.05, 0.04], highlightTint: [0.05, 0.05, 0.03], crossover: 0.7,
      grainSize: 0.62, grainDensity: 0.68, grainClump: 0.66, grainChroma: 0.62,
      halationTint: [1, 0.48, 0.24], halationBase: 0.4, bloom: 0.36,
    }),
    notes: {
      tonal: 'Base fog has lifted the blacks and eaten the contrast. Speed is well below the marking.',
      grain: 'Coarse, clumped and uneven across the frame.',
      color: 'Unpredictable crossover — usually magenta shadows and sallow highlights, but no two rolls agree.',
      highlight: 'Flat and chalky.',
      shadow: 'Never reaches black. Fog sets a permanent floor.',
      history: 'An unmarked roll of uncertain storage history. Behaviour is a reading of what age does to a colour emulsion, not a reproduction of a specific stock.',
    },
    development: ['normal', 'push', 'pull', 'cross-process'],
    developers: ['c41'],
    swatch: ['#2b2422', '#948069', '#eee5cf'],
  },
];

export const MATERIALS_BY_ID = new Map(MATERIALS.map((m) => [m.id, m]));

export const getMaterial = (id: string): Material =>
  MATERIALS_BY_ID.get(id) ?? MATERIALS[4];

/* ---- taxonomy used by the archive filters ---- */
export const ERAS: { id: Material['era']; label: string }[] = [
  { id: '1800s', label: '1800s' },
  { id: '1900-1929', label: '1900 – 1929' },
  { id: '1930-1949', label: '1930 – 1949' },
  { id: '1950-1969', label: '1950 – 1969' },
  { id: '1970-1989', label: '1970 – 1989' },
  { id: '1990-2009', label: '1990 – 2009' },
  { id: '2010-present', label: '2010 – Present' },
];

export const KINDS: { id: Material['kind']; label: string }[] = [
  { id: 'bw-negative', label: 'Black & White' },
  { id: 'color-negative', label: 'Colour Negative' },
  { id: 'color-reversal', label: 'Colour Reversal' },
  { id: 'instant', label: 'Instant' },
  { id: 'motion-picture', label: 'Motion Picture' },
  { id: 'early-process', label: 'Early Processes' },
  { id: 'experimental', label: 'Experimental' },
];

export const FORMATS: { id: Material['formats'][number]; label: string }[] = [
  { id: 'large-format', label: 'Large Format' },
  { id: 'medium-format', label: 'Medium Format' },
  { id: '35mm', label: '35mm' },
  { id: '16mm', label: '16mm' },
  { id: 'super-8', label: 'Super 8' },
  { id: 'instant', label: 'Instant' },
  { id: 'plate', label: 'Plate' },
];

export const MANUFACTURERS = Array.from(
  new Set(MATERIALS.map((m) => m.manufacturer)),
).sort();

export const KIND_LABEL: Record<Material['kind'], string> = {
  'bw-negative': 'B&W Negative',
  'color-negative': 'Colour Negative',
  'color-reversal': 'Colour Reversal',
  instant: 'Instant',
  'motion-picture': 'Motion Picture',
  'early-process': 'Early Process',
  experimental: 'Experimental',
};

export const FORMAT_LABEL: Record<Material['formats'][number], string> = {
  'large-format': 'Large Format',
  'medium-format': 'Medium Format',
  '35mm': '35mm',
  '16mm': '16mm',
  'super-8': 'Super 8',
  instant: 'Instant',
  plate: 'Plate',
};

export const FIDELITY_LABEL: Record<Material['fidelity'], string> = {
  documented: 'Documented',
  reconstructed: 'Reconstructed',
  interpretation: 'Artistic interpretation',
};

export const FIDELITY_NOTE: Record<Material['fidelity'], string> = {
  documented:
    'Behaviour derived from published manufacturer data and measured references.',
  reconstructed:
    'Assembled from partial references. Some behaviour is inferred rather than measured.',
  interpretation:
    'An artistic reading of the process. This is not a chemical reproduction.',
};
